### ISSUE TITLE
Any plans for hal_ros2_control?

### ISSUE THREAD

**Issue by samuk** [tormach/hal_ros_control#4]
Hi I was interested in this approach, but working in a ROS2 environment. Do you have any plans for a ROS2 version?

[Also raised on MachineKoder article](https://machinekoder.com/machinekit-ros-industrial-robot/#comment-111069)

**Comment by zultron** [comment]
Yes, actually, I believe there will be a ROS2 port within the next couple of months.  You can watch this repo for news about that.  Thanks, I'm glad to hear about your interest!

**Comment by zultron** [comment]
I'll actually leave this issue open, since there's no other issue tracking the upcoming ROS2 port.

**Comment by zultron** [comment]
Development has started on the ROS2 port.  I'm shooting for a first version before January.

**Comment by zultron** [comment]
Tormach sponsored this work, so the repo has been moved to their org.

Initial non-working ROS2 PR will be submitted later today.

**Comment by zultron** [comment]
Repo at https://github.com/tormach/hal_ros_control

First PR at https://github.com/tormach/hal_ros_control/pull/6

First working version targeted for Jan. 2022!

________________________________________

**Comment by zultron** [comment]
The ROS2 port is now working *in tests*; see PR #10  (which includes everything from #7, #8, #9).  It still has a few issues, esp. shutdown isn't working properly and it hasn't been tested on real hardware.  But it's a start!  Testers are very welcome.

**Comment by zultron** [comment]
As of PR #15, I consider this work substantially complete.  I'm closing out this issue.
